services:
  - type: worker
    name: al-shef-bot-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot/main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GIGACHAT_AUTH
        sync: false
      - key: LOG_LEVEL
        value: INFO

databases:
  - name: alshef_db
    plan: free
    databaseName: alshef_db
    user: alshef_user